[project]
name = "soundclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-speech>=2.34.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "sounddevice>=0.5.3",
]
